version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql
  web:
    build: .
    depends_on:
      - db
    image: elixir:1.5
    ports: 
      - "4000:4000"
    volumes:
      - ./:/app
volumes:
  dbdata: